name: e_tym
description: "Application e-commerce pour chaussures, habits et accessoires"
publish_to: 'none'
version: 1.0.0+1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#F5F0D7"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  
  # UI et utilitaires
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  
  # State management
  provider: ^6.1.2
  
  # Images et permissions
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  
  # HTTP
  http: ^1.2.0
  
  # CinetPay (NOUVEAU)
  cinetpay: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/